name: Lint changes

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - name: Run ESLint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: eslint.config.js
          # escape_paths: false - needed if using SvelteKit parenthesis in routes
          # skip_annotations: true
          extra_args: --quiet
          file_extensions: |
            **/*.ts
            **/*.js
            **/*.svelte
            **/*.composition
            **/*.html
            **/*.markdown
            **/*.json
            **/*.yml
