name: Playwright E2E Tests

on:
  deployment_status:

jobs:
  run-e2e:
    name: Playwright E2E Tests
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.3

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm -F site test:e2e
        env:
          CI: true
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}