# https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment helps a little - beware syntax issues
name: Playwright E2E and Component Tests

on:
  deployment_status

jobs:
  run-e2e:
    name: Playwright E2E and Component Tests
    if: github.event.deployment_status.state == 'success' && (github.event.deployment_status.environment == 'Production' || github.event.deployment_status.environment == 'Preview')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy #https://playwright.dev/docs/ci#github-actions-via-containers - keep version in sync with installed package

    steps:
      - name: Allow image commit and branch name extraction
        run: git config --system --add safe.directory /__w/kitbook/kitbook # --global might work instead of --system, https://github.com/actions/checkout/issues/1169

      - name: Get Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{ github.event.deployment_status.deployment.ref }}'

      - name: Extract branch name
        run: echo "GITHUB_BRANCH=$(git show -s --pretty=%D HEAD | tr -s ',' '\n' | sed 's/^ //' | grep -e 'origin/' | head -1 | sed 's/\origin\///g')" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install Dependencies
        run: pnpm install

      - name: Run Playwright e2e tests
        run: pnpm test:e2e basic # remove basic to add snapshotting in
        env:
          CI: true
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}

      # - name: Commit Changed Component Snapshots
      #   uses: stefanzweifel/git-auto-commit-action@v4.16.0
      #   if: github.event.deployment_status.environment != 'Production'
      #   with:
      #     commit_message: '[Updated Component Snapshots]'
      #     branch: ${{ steps.extract_branch.outputs.GITHUB_BRANCH }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send E2E Results to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
        uses: adamkdean/simple-slack-notify@master
        with:
          status: ${{ job.status }}
          failure_text: 'E2E Tests for (#${env.GITHUB_RUN_NUMBER}) on ${{ github.event.deployment_status.target_url }} failed'
          cancelled_text: 'E2E Tests for (#${env.GITHUB_RUN_NUMBER}) cancelled'
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
