name: Unit Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  unit_test:
    name: Unit Test PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      # - name: Svelte Check
      #   run: npm run check
      
      - name: Run Vitest Unit Tests
        run: npm run test

      - name: Slack E2E Results Notification
        uses: 8398a7/action-slack@v3 # https://action-slack.netlify.app/
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          # channel: '#github'
          # failure_text: 'Unit Tests for (#${env.GITHUB_RUN_NUMBER}) failed'
          # fields: |
          #   [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
